version: '2'

networks:
  xwiki-nw:
    driver: bridge
services:
  postgresql:
    image: postgres:9.5.3
    container_name: xwiki-pgsql
    environment:
      POSTGRES_USER: postgresql-xwiki
      POSTGRES_PASSWORD: postgresql-xwiki
      POSTGRES_DB: postgresql-xwiki
    networks:
      - xwiki-nw
    stdin_open: true
    tty: true
    restart: always
  xwiki-tomcat:
    build: ./xwiki-tomcat
    image: xwiki-tomcat
    container_name: xwiki-tomcat
    environment:
      POSTGRES_INSTANCE: xwiki-pgsql
      POSTGRES_USER: postgresql-xwiki
      POSTGRES_PASSWORD: postgresql-xwiki
      POSTGRES_DB: postgresql-xwiki
    ports:
     - "8080:8080"
    networks:
      - xwiki-nw
