apiVersion: v1
kind: Endpoints
metadata:
  name: gluster-cluster
subsets:
- addresses:              
  - ip: 10.0.0.1
  ports:                  
  - port: 1
    protocol: TCP
- addresses:
  - ip: 10.0.0.2
  ports:
  - port: 1
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: gluster-cluster
spec:
  ports:
  - port: 1
